name: Earthly +build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: 
          - recipe: namada
            tag_suffix: namada
          - recipe: wasm
            tag_suffix: wasm

    env:
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.14
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Determine Image Tag
      id: tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "IMAGE_TAG=-main" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=-${{ github.ref_name }}" >> $GITHUB_ENV
        fi
    - name: Run build
      run: earthly +${{ matrix.command.recipe }} --tag=${{ matrix.command.tag_suffix }}${{ env.IMAGE_TAG }}
      env:
        EARTHLY_PUSH: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}